### PR TITLE
fixed possible undefined parameters

### PR DESCRIPTION
**Pull request by giano**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment "._ok\W+to\W+test._"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@giano thank you for the pull request, I have landed the patch via ec910fe63 and released as `v20.1.1`. Please send your pull requests against the branch `v20.x` in the future.

**Comment by giano** [comment]
ok. Thanks for the fast patch!

**Pull request closed without merging**
